services:
  traefik:
    image: traefik:v2.11.0
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:8888
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal
    ports:
      - 80:8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  idaho-runs:
    image: nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.idaho-runs.rule=Host(`localhost`)
      - traefik.http.routers.idaho-runs.entrypoints=web
      - traefik.http.middlewares.idaho-runs.ratelimit.average=100
    volumes:
      - ./website/:/usr/share/nginx/html
